name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - lily58-left
          - lily58-right
          - corne-left
          - corne-right
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y device-tree-compiler
      - uses: actions/cache@v4
        with:
          path: .zmk
          key: west-${{ hashFiles('config/west.yml') }}
      - uses: jdx/mise-action@v3
        with:
          cache: true
          experimental: true
      - run: mise run build:${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: .zmk/build/*/zephyr/zmk.uf2
